In [1]:
import numpy as np
import gym

env = gym.make('FrozenLake-v0')

[2017-07-10 23:18:19,003] Making new env: FrozenLake-v0


In [3]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)


In [5]:
print("Score over time: " +  str(sum(rList)/num_episodes))


Score over time: 0.609


In [7]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[  1.01064310e-01   1.22986220e-02   1.38040134e-02   1.65117295e-02]
 [  3.20359662e-03   1.05628180e-04   1.55982842e-03   1.94917262e-01]
 [  1.43911689e-03   0.00000000e+00   8.49190739e-03   2.41103323e-01]
 [  3.30945899e-04   0.00000000e+00   2.29637760e-04   5.67937360e-02]
 [  1.41332750e-01   1.16480047e-03   1.44006046e-03   2.45491226e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.18441050e-01   2.14843162e-09   5.88187034e-04   1.64372748e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.18604713e-03   0.00000000e+00   1.05300488e-03   1.04763478e-01]
 [  0.00000000e+00   5.69206664e-01   0.00000000e+00   0.00000000e+00]
 [  7.97222178e-01   9.54644181e-04   4.78206280e-05   3.02491129e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   4.88165917e-01   0

# Q-Table Learning

In [1]:
import gym
import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
env = gym.make('FrozenLake-v0')

[2017-07-10 02:34:16,591] Making new env: FrozenLake-v0


In [11]:
import time
start_time = time.time()
Q_th = torch.zeros([env.observation_space.n, env.action_space.n])
lr = 0.8
y = 0.95
num_episode = 2000

rList = []
for i in range(num_episode):
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    
    while j < 1:#99:
        j += 1
        aa_th = Q_th[s,:] + torch.randn(1, env.action_space.n)*(1./(i+1))
        _, a_th = torch.max(aa_th, 0)
        s1, r, d, _ = env.step(a_th[0])        
        print(type(s1), type(r), type(d))
        update = r + y*torch.max(Q_th[s1,:]) - Q_th[s, a_th[0]]
        Q_th[s, a_th[0]] = Q_th[s, a_th[0]] + lr*(update)
        rAll += r
        s = s1
        if d == True:
            break
        rList.append(rAll)
        print(rAll)
print(time.time() - start_time)        

<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class

<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class

<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class

<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class

0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <c

<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class

<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class 'float'> <class 'bool'>
0.0
<class 'int'> <class

In [4]:
start_time = time.time()
print("Score over time: " + str(sum(rList)/num_episode))
print(time.time() - start_time)

Score over time: 0.0
0.0029439926147460938


In [5]:
print('Final Q-table values')
print(Q_th)

Final Q-table values

 0.2230  0.0058  0.0060  0.0057
 0.0012  0.0008  0.0013  0.1892
 0.1618  0.0023  0.0007  0.0040
 0.0011  0.0003  0.0010  0.0039
 0.1490  0.0005  0.0006  0.0002
 0.0000  0.0000  0.0000  0.0000
 0.0000  0.0000  0.0156  0.0000
 0.0000  0.0000  0.0000  0.0000
 0.0000  0.0011  0.0001  0.1941
 0.0012  0.5588  0.0017  0.0002
 0.2011  0.0000  0.0000  0.0000
 0.0000  0.0000  0.0000  0.0000
 0.0000  0.0000  0.0000  0.0000
 0.0000  0.0040  0.8734  0.0002
 0.0000  0.0000  0.8496  0.0000
 0.0000  0.0000  0.0000  0.0000
[torch.FloatTensor of size 16x4]



# Q - Networks

In [ ]:
# Define a model
# input to a model
Q_th = torch.zeros([env.observation_space.n, env.action_space.n])
# compute first hidden layer (define a weight matrix, and a non-linearity)
W_1 = torch.randn(16, 4)
a_1 = torch.nn.relu(torch.mul(Q_th, W_1))
# compute the output node
